[package]
name = "model3d-gl"
version = "0.1.0"
edition = "2021"

[dependencies]
geo-nd   = "0.1.0"
gl = "0.10.0"
indent-display = "0.1.1"
model3d-base = { path="../model3d-rs" }

[dependencies.web-sys]
features = [
  'console',
  'CanvasRenderingContext2d',
  'Document',
  'EventTarget',
  'Element',
  'HtmlCanvasElement',
  'HtmlElement',
  'MouseEvent',
  'WebGlBuffer',
  'WebGlVertexArrayObject',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlUniformLocation',
  'Window',
]
version = ">=0.3.40"

